ALTER TABLE activities ADD COLUMN IF NOT EXISTS operator_name TEXT NOT NULL DEFAULT '';
ALTER TABLE activities ADD COLUMN IF NOT EXISTS operator_phone TEXT;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS badge TEXT NOT NULL DEFAULT '';
ALTER TABLE activities ADD COLUMN IF NOT EXISTS includes TEXT[] NOT NULL DEFAULT '{}';
ALTER TABLE activities ADD COLUMN IF NOT EXISTS price_unit TEXT NOT NULL DEFAULT 'person';
ALTER TABLE activities ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now();

ALTER TABLE academies ADD COLUMN IF NOT EXISTS training_packages TEXT[] NOT NULL DEFAULT '{}';
ALTER TABLE academies ADD COLUMN IF NOT EXISTS featured BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE academies ADD COLUMN IF NOT EXISTS latitude NUMERIC;
ALTER TABLE academies ADD COLUMN IF NOT EXISTS longitude NUMERIC;
ALTER TABLE academies ADD COLUMN IF NOT EXISTS active BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE venues ADD COLUMN IF NOT EXISTS active BOOLEAN NOT NULL DEFAULT TRUE;
