import Image from "next/image";
import Link from "next/link";
import { Play,Radio } from "lucide-react";
import { query } from "@/lib/db";
import { GameCard } from "@/components/game-card";
import { getGames,gameDate,type Game } from "@/lib/data";
import { sports,sportLabels,sportImages } from "@/lib/brand";
type Stream={id:string;game_id:string;title:string;sport:string;image_url:string;status:string;venue_name:string};
export default async function Watch(){const [streams,{rows:games},recordings]=await Promise.all([query<Stream>("SELECT s.id,s.game_id,s.status,g.title,g.sport,g.image_url,v.name AS venue_name FROM streams s JOIN games g ON g.id=s.game_id JOIN venues v ON v.id=g.venue_id WHERE s.status='LIVE' AND s.visibility='PUBLIC'"),getGames(),query<{id:string;title:string;image_url:string;starts_at:string}>("SELECT r.id,g.title,g.image_url,g.starts_at FROM recordings r JOIN games g ON g.id=r.game_id WHERE r.status='READY' AND r.visibility='PUBLIC' ORDER BY g.starts_at DESC LIMIT 6")]);return <main className="page"><div className="container"><div className="page-head"><h1>Watch</h1><p>Catch the game, wherever you are.</p></div><div className="section-head"><h2><Radio size={21} style={{display:"inline",color:"#e12e2e"}}/> Live now</h2></div>{streams.length?<div className="grid-3">{streams.map(s=><Link className="card" href={`/watch/live/${s.id}`} key={s.id}><div style={{position:"relative",height:190}}><Image src={s.image_url} alt="" fill sizes="33vw"/><span className="badge" style={{position:"absolute",top:12,left:12,background:"#e12e2e",color:"#fff"}}>LIVE</span></div><div style={{padding:15}}><h3>{s.title}</h3><p>{s.venue_name}</p><span className="inline-link">Watch live →</span></div></Link>)}</div>:<div className="empty"><h3>No games live right now</h3><p>Explore upcoming matches below.</p></div>}<div className="section-head" style={{marginTop:40}}><h2>Upcoming games</h2></div><div className="game-grid">{games.slice(0,3).map((g:Game)=><GameCard game={g} key={g.id}/>)}</div><div className="section-head" style={{marginTop:44}}><h2>Recent games</h2><Link className="section-link" href="/watch/archive">Browse archive →</Link></div>{recordings.length?<div className="grid-3">{recordings.map(r=><Link className="card" href={`/watch/${r.id}`} key={r.id}><div style={{height:170,position:"relative"}}><Image src={r.image_url} alt="" fill sizes="33vw"/></div><div style={{padding:14}}><strong>{r.title}</strong><p className="muted">{gameDate(r.starts_at)}</p></div></Link>)}</div>:<p className="muted">Recordings appear here after streams are processed.</p>}<div className="section-head" style={{marginTop:45}}><h2>Browse by sport</h2></div><div className="grid-4">{sports.map(s=><Link className="card" href={`/watch/archive?sport=${s}`} key={s}><div style={{height:120,position:"relative"}}><Image src={sportImages[s]} alt="" fill sizes="25vw"/></div><div style={{padding:10,fontWeight:750}}>{sportLabels[s]} <Play size={13} style={{display:"inline"}}/></div></Link>)}</div></div></main>}
