"use server";
import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { currentUser, login, signup, signOut, requireManager, requestPasswordReset,resetPassword } from "@/lib/auth";
import { bookGame, cancelBooking, cancelGame } from "@/lib/booking";
import { addScoreEvent, finalizeGame, generateTeams, undoScoreEvent } from "@/lib/competition";
import { eventSchema } from "@/lib/scoring";
import { controlGameClock } from "@/lib/clock";
import { query, one } from "@/lib/db";
import { randomUUID } from "node:crypto";
import { z } from "zod";
import { createGameStream,endGameStream,type Visibility } from "@/lib/streaming";
import { DateTime } from "luxon";

const errorText=(e:unknown)=>e instanceof Error?e.message:"Something went wrong. Please try again.";
async function organizerFor(gameId:string){const user=await requireManager(gameId);const game=await one<{organizer_id:string}>("SELECT organizer_id FROM games WHERE id=$1",[gameId]);if(!game||!(game.organizer_id===user.id||["ADMIN","SUPER_ADMIN"].includes(user.role)))throw new Error("Organizer access is required.");return user;}
export async function loginAction(form:FormData){let error="";try{await login(String(form.get("email")||""),String(form.get("password")||""));}catch(e){error=errorText(e);}if(error)redirect(`/login?error=${encodeURIComponent(error)}`);redirect("/games");}
export async function signupAction(form:FormData){let error="";try{await signup(Object.fromEntries(form));}catch(e){error=errorText(e);}if(error)redirect(`/signup?error=${encodeURIComponent(error)}`);redirect("/onboarding/sports");}
export async function logoutAction(){await signOut();redirect("/");}
export async function bookAction(form:FormData){
  const id=String(form.get("gameId")||"");let error="",result:Awaited<ReturnType<typeof bookGame>>|null=null;
  try{const user=await currentUser();if(!user)redirect(`/login?next=/games/${id}`);result=await bookGame(id,user!.id,form.get("recordingAck")==="on");}catch(e){if(e&&typeof e==="object"&&"digest" in e)throw e;error=errorText(e);}
  if(error)redirect(`/games/${id}?error=${encodeURIComponent(error)}`);
  revalidatePath(`/games/${id}`);revalidatePath("/games");
  if(result?.kind==="waitlist")redirect(`/games/${id}?notice=${encodeURIComponent(`You're #${result.position} on the waitlist.`)}`);
  redirect(`/bookings?notice=${encodeURIComponent(`You're in! Booking reference ${result?.reference}`)}`);
}
export async function cancelBookingAction(form:FormData){const user=await currentUser();if(!user)redirect("/login");let error="";try{await cancelBooking(String(form.get("bookingId")),user.id);}catch(e){error=errorText(e);}revalidatePath("/bookings");redirect(error?`/bookings?error=${encodeURIComponent(error)}`:"/bookings?notice=Booking%20cancelled");}
export async function onboardingAction(form:FormData){const user=await currentUser();if(!user)redirect("/login");const selected=form.getAll("sports").map(String).filter(s=>["football","basketball","dodgeball","tennis"].includes(s));for(const sport of selected)await query("INSERT INTO sport_profiles(user_id,sport,position,preferred_foot,dominant_hand,tennis_preference,skill) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(user_id,sport) DO UPDATE SET position=$3,preferred_foot=$4,dominant_hand=$5,tennis_preference=$6,skill=$7",[user.id,sport,form.get(`${sport}_position`)||null,form.get("preferred_foot")||null,form.get("dominant_hand")||null,form.get("tennis_preference")||null,form.get(`${sport}_skill`)||"Intermediate"]);redirect(`/profile/${user.username}`);}
export async function scoreAction(form:FormData){const id=String(form.get("gameId"));let error="";try{const user=await requireManager(id);const input=eventSchema.parse({type:form.get("type"),team:form.get("team"),playerId:form.get("playerId")||undefined,assistId:form.get("assistId")||undefined,period:form.get("period")||undefined,clockSeconds:form.get("clockSeconds")||undefined});await addScoreEvent(id,user.id,input);}catch(e){error=errorText(e);}revalidatePath(`/games/${id}/score`);redirect(error?`/admin/games/${id}/scorekeeper?error=${encodeURIComponent(error)}`:`/admin/games/${id}/scorekeeper`);}
export async function clockAction(form:FormData){const id=String(form.get("gameId"));let error="";try{const user=await requireManager(id);const command=z.enum(["START","PAUSE","RESET","NEXT_PERIOD"]).parse(form.get("command"));await controlGameClock(id,user.id,command);}catch(e){error=errorText(e);}revalidatePath(`/games/${id}/score`);redirect(error?`/admin/games/${id}/scorekeeper?error=${encodeURIComponent(error)}`:`/admin/games/${id}/scorekeeper`);}
export async function undoAction(form:FormData){const id=String(form.get("gameId"));let error="";try{const user=await requireManager(id);await undoScoreEvent(id,user.id);}catch(e){error=errorText(e);}revalidatePath(`/games/${id}/score`);redirect(error?`/admin/games/${id}/scorekeeper?error=${encodeURIComponent(error)}`:`/admin/games/${id}/scorekeeper`);}
export async function finalizeAction(form:FormData){const id=String(form.get("gameId"));let error="";try{const user=await requireManager(id);await finalizeGame(id,user.id);}catch(e){error=errorText(e);}revalidatePath(`/games/${id}`);redirect(error?`/admin/games/${id}/scorekeeper?error=${encodeURIComponent(error)}`:`/games/${id}/score?notice=Result%20final`);}
export async function teamsAction(form:FormData){const id=String(form.get("gameId"));let error="";try{await organizerFor(id);await generateTeams(id);}catch(e){error=errorText(e);}redirect(error?`/admin/games/${id}?error=${encodeURIComponent(error)}`:`/admin/games/${id}?notice=Teams%20generated`);}
const gameSchema=z.object({sport:z.enum(["football","basketball","dodgeball","tennis"]),title:z.string().min(5),format:z.string().min(2),venueId:z.string().uuid(),startsAt:z.iso.datetime({local:true}),capacity:z.coerce.number().int().min(2).max(100),price:z.coerce.number().min(0).max(100),skill:z.string(),description:z.string().max(2000),recordingEnabled:z.boolean(),tennisBestOf:z.enum(["3","5"]).default("3"),tennisTiebreak:z.boolean()});
export async function createGameAction(form:FormData){const user=await currentUser();if(!user)redirect("/login");if(!["ORGANIZER","ADMIN","SUPER_ADMIN"].includes(user.role))redirect("/admin?error=Organizer%20access%20required");let error="",id="";try{const input=gameSchema.parse({sport:form.get("sport"),title:form.get("title"),format:form.get("format"),venueId:form.get("venueId"),startsAt:form.get("startsAt"),capacity:form.get("capacity"),price:form.get("price"),skill:form.get("skill"),description:form.get("description"),recordingEnabled:form.get("recordingEnabled")==="on",tennisBestOf:form.get("tennisBestOf")||"3",tennisTiebreak:form.get("tennisTiebreak")==="on"});const venue=await one<{image_url:string}>("SELECT image_url FROM venues WHERE id=$1 AND $2=ANY(sports)",[input.venueId,input.sport]);if(!venue)throw new Error("Choose a venue that supports this sport.");const zoned=DateTime.fromISO(input.startsAt,{zone:"Asia/Amman"});if(!zoned.isValid||zoned.toMillis()<=Date.now())throw new Error("Choose a future start time in Amman.");id=randomUUID();const start=zoned.toJSDate();await query("INSERT INTO games(id,sport,title,format,description,venue_id,organizer_id,starts_at,ends_at,capacity,price_fils,skill,image_url,recording_enabled,stream_enabled,score_config) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$14,$15)",[id,input.sport,input.title,input.format,input.description,input.venueId,user.id,start,new Date(start.getTime()+90*60000),input.capacity,Math.round(input.price*1000),input.skill,venue.image_url,input.recordingEnabled,JSON.stringify(input.sport==="tennis"?{tennisBestOf:Number(input.tennisBestOf),tennisTiebreak:input.tennisTiebreak}:{})]);}catch(e){error=errorText(e);}redirect(error?`/admin/games/new?error=${encodeURIComponent(error)}`:`/admin/games/${id}`);}
export async function postAction(form:FormData){const user=await currentUser();if(!user)redirect("/login");const body=String(form.get("body")||"").trim();if(body.length>0&&body.length<=1000)await query("INSERT INTO posts(id,user_id,body) VALUES($1,$2,$3)",[randomUUID(),user.id,body]);revalidatePath("/community");redirect("/community");}
export async function likeAction(form:FormData){const user=await currentUser();if(!user)redirect("/login");await query("INSERT INTO post_likes(post_id,user_id) VALUES($1,$2) ON CONFLICT DO NOTHING",[String(form.get("postId")),user.id]);revalidatePath("/community");redirect("/community");}
export async function commentAction(form:FormData){const user=await currentUser();if(!user)redirect("/login");const body=String(form.get("body")||"").trim();if(body.length>0&&body.length<=500)await query("INSERT INTO post_comments(id,post_id,user_id,body) VALUES($1,$2,$3,$4)",[randomUUID(),String(form.get("postId")),user.id,body]);revalidatePath("/community");redirect("/community");}
export async function joinTournamentAction(form:FormData){const user=await currentUser();if(!user)redirect("/login");const id=String(form.get("id")),teamName=String(form.get("teamName")||"").trim().slice(0,60)||null;const tournament=await one<{status:string;starts_at:string}>("SELECT status,starts_at FROM tournaments WHERE id=$1",[id]);if(!tournament||tournament.status!=="OPEN"||new Date(tournament.starts_at)<=new Date())redirect(`/tournaments/${id}?error=Registration%20is%20closed`);await query("INSERT INTO tournament_entries(tournament_id,user_id,team_name) VALUES($1,$2,$3) ON CONFLICT DO NOTHING",[id,user.id,teamName]);revalidatePath("/tournaments");redirect(`/tournaments/${id}?notice=You%20joined%20the%20tournament`);}
export async function createStreamAction(form:FormData){const id=String(form.get("gameId"));let error="";try{await organizerFor(id);const visibility=z.enum(["PUBLIC","PARTICIPANTS_ONLY","UNLISTED","PRIVATE"]).parse(form.get("visibility"));await createGameStream(id,visibility as Visibility);}catch(e){error=errorText(e);}redirect(error?`/admin/games/${id}?error=${encodeURIComponent(error)}`:`/admin/games/${id}?notice=Stream%20created`);}
export async function endStreamAction(form:FormData){const id=String(form.get("gameId"));let error="";try{await organizerFor(id);await endGameStream(id);}catch(e){error=errorText(e);}redirect(error?`/admin/games/${id}?error=${encodeURIComponent(error)}`:`/admin/games/${id}?notice=Stream%20ended`);}
export async function forgotAction(form:FormData){let error="",devUrl:string|null=null;try{devUrl=await requestPasswordReset(String(form.get("email")||""));}catch(e){error=errorText(e);}if(error)redirect(`/forgot-password?error=${encodeURIComponent(error)}`);redirect(`/forgot-password?sent=1${devUrl?`&devUrl=${encodeURIComponent(devUrl)}`:""}`);}
export async function resetPasswordAction(form:FormData){const token=String(form.get("token")||"");let error="";try{const password=String(form.get("password")||"");if(password!==form.get("confirm"))throw new Error("Passwords do not match.");await resetPassword(token,password);}catch(e){error=errorText(e);}if(error)redirect(`/reset-password/${token}?error=${encodeURIComponent(error)}`);redirect("/login?notice=Password%20updated");}
export async function contactAction(form:FormData){let error="";try{const input=z.object({name:z.string().trim().min(2).max(80),email:z.email(),body:z.string().trim().min(10).max(2000)}).parse({name:form.get("name"),email:form.get("email"),body:form.get("body")});const recent=await one<{n:string}>("SELECT count(*)::text AS n FROM contact_messages WHERE email=$1 AND created_at>now()-interval '15 minutes'",[input.email]);if(Number(recent?.n||0)>=3)throw new Error("Please wait before sending another message.");await query("INSERT INTO contact_messages(id,name,email,body) VALUES($1,$2,$3,$4)",[randomUUID(),input.name,input.email,input.body]);}catch(e){error=errorText(e);}redirect(error?`/contact?error=${encodeURIComponent(error)}`:"/contact?sent=1");}
export async function reviewAction(form:FormData){const id=String(form.get("gameId")||"");const user=await currentUser();if(!user)redirect("/login");let error="";try{const input=z.object({venue:z.coerce.number().int().min(1).max(5),organization:z.coerce.number().int().min(1).max(5),experience:z.coerce.number().int().min(1).max(5),body:z.string().trim().max(1000)}).parse({venue:form.get("venue"),organization:form.get("organization"),experience:form.get("experience"),body:form.get("body")||""});const eligible=await one<{venue_id:string}>("SELECT g.venue_id FROM games g JOIN bookings b ON b.game_id=g.id WHERE g.id=$1 AND b.user_id=$2 AND g.status='COMPLETED' AND b.status='COMPLETED'",[id,user.id]);if(!eligible)throw new Error("Only players who completed this game can review it.");await query("INSERT INTO reviews(id,game_id,user_id,venue_rating,organization_rating,experience_rating,body) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(game_id,user_id) DO UPDATE SET venue_rating=$4,organization_rating=$5,experience_rating=$6,body=$7",[randomUUID(),id,user.id,input.venue,input.organization,input.experience,input.body]);await query("UPDATE venues SET rating=COALESCE((SELECT ROUND(AVG(r.venue_rating)::numeric,1) FROM reviews r JOIN games g ON g.id=r.game_id WHERE g.venue_id=$1),rating) WHERE id=$1",[eligible.venue_id]);}catch(e){error=errorText(e);}revalidatePath(`/games/${id}`);redirect(error?`/games/${id}?tab=reviews&error=${encodeURIComponent(error)}`:`/games/${id}?tab=reviews&notice=Review%20saved`);}
export async function markNotificationsReadAction(){const user=await currentUser();if(!user)redirect("/login");await query("UPDATE notifications SET read_at=now() WHERE user_id=$1 AND read_at IS NULL",[user.id]);revalidatePath("/notifications");redirect("/notifications");}
export async function selectMvpAction(form:FormData){const id=String(form.get("gameId"));let error="";try{const user=await requireManager(id),nominee=String(form.get("playerId"));const game=await one<{organizer_id:string;finalized_at:string|null}>("SELECT organizer_id,finalized_at FROM games WHERE id=$1",[id]);if(!game||game.finalized_at||!(game.organizer_id===user.id||["ADMIN","SUPER_ADMIN"].includes(user.role)))throw new Error("Only the organizer can select an MVP before finalization.");const exists=await one("SELECT id FROM bookings WHERE game_id=$1 AND user_id=$2 AND status IN ('CONFIRMED','COMPLETED')",[id,nominee]);if(!exists)throw new Error("Choose a booked player.");await query("UPDATE games SET mvp_id=$1 WHERE id=$2 AND finalized_at IS NULL",[nominee,id]);await query("INSERT INTO audit_logs(id,actor_id,action,entity,entity_id,new_data) VALUES($1,$2,'MVP_SELECTED','game',$3,$4)",[randomUUID(),user.id,id,JSON.stringify({mvpId:nominee})]);}catch(e){error=errorText(e);}redirect(error?`/admin/games/${id}?error=${encodeURIComponent(error)}`:`/admin/games/${id}?notice=MVP%20selected`);}
export async function voteMvpAction(form:FormData){const id=String(form.get("gameId")),nominee=String(form.get("playerId"));const user=await currentUser();if(!user)redirect("/login");let error="";try{const game=await one<{mvp_enabled:boolean;finalized_at:string|null}>("SELECT mvp_enabled,finalized_at FROM games WHERE id=$1",[id]);if(!game?.mvp_enabled||game.finalized_at)throw new Error("MVP voting is closed.");const [voter,player]=await Promise.all([one("SELECT id FROM bookings WHERE game_id=$1 AND user_id=$2 AND status IN ('CONFIRMED','COMPLETED')",[id,user.id]),one("SELECT id FROM bookings WHERE game_id=$1 AND user_id=$2 AND status IN ('CONFIRMED','COMPLETED')",[id,nominee])]);if(!voter||!player)throw new Error("Only booked players can vote for another booked player.");const existing=await one("SELECT voter_id FROM mvp_votes WHERE game_id=$1 AND voter_id=$2",[id,user.id]);if(existing)throw new Error("You have already voted.");await query("INSERT INTO mvp_votes(game_id,voter_id,nominee_id) VALUES($1,$2,$3)",[id,user.id,nominee]);}catch(e){error=errorText(e);}redirect(error?`/games/${id}/mvp?error=${encodeURIComponent(error)}`:`/games/${id}/mvp?notice=Vote%20recorded`);}
export async function cancelGameAction(form:FormData){const id=String(form.get("gameId"));let error="";try{const user=await requireManager(id),game=await one<{organizer_id:string}>("SELECT organizer_id FROM games WHERE id=$1",[id]);if(!game||!(game.organizer_id===user.id||["ADMIN","SUPER_ADMIN"].includes(user.role)))throw new Error("Only the organizer can cancel this game.");await cancelGame(id,user.id);}catch(e){error=errorText(e);}revalidatePath("/games");redirect(error?`/admin/games/${id}?error=${encodeURIComponent(error)}`:`/admin/games/${id}?notice=Game%20cancelled`);}
export async function adminCancelBookingAction(form:FormData){const id=String(form.get("bookingId"));let error="";try{const booking=await one<{game_id:string;user_id:string}>("SELECT game_id,user_id FROM bookings WHERE id=$1",[id]);if(!booking)throw new Error("Booking not found.");const user=await organizerFor(booking.game_id);await cancelBooking(id,booking.user_id);await query("INSERT INTO audit_logs(id,actor_id,action,entity,entity_id) VALUES($1,$2,'PLAYER_REMOVED','booking',$3)",[randomUUID(),user.id,id]);}catch(e){error=errorText(e);}redirect(error?`/admin/bookings?error=${encodeURIComponent(error)}`:"/admin/bookings?notice=Booking%20cancelled%20and%20refunded");}
