import Link from "next/link";
import { brand } from "@/lib/brand";

export default function Terms(){return <main className="page"><article className="container legal-page"><div className="page-head"><h1>Terms of use</h1><p>Rules for using PlayUp</p></div>
<p className="legal-updated">Last updated: 3 October 2026</p>
<h2>Operator and acceptance</h2><p>PlayUp is operated by {brand.operatorName}.{brand.operatorAddress&&<> The operator address is {brand.operatorAddress}.</>} By creating an account or making a booking, you agree to these terms and the <Link className="inline-link" href="/privacy">Privacy policy</Link>.</p>
<h2>Eligibility</h2><p>You must be at least {brand.minimumAge}, or use PlayUp with the involvement and consent of a parent or legal guardian, and be legally able to enter this agreement. Account information must be accurate and you are responsible for activity under your account.</p>
<h2>Bookings and payment</h2><p>PlayUp helps people discover and join sports games, courts, academies, and activities. Unless a listing clearly says otherwise, bookings are paid in cash directly to the venue, academy, or organizer on arrival. PlayUp does not currently charge cards online.</p>
<h2>Cancellations and no-shows</h2><p>You may cancel an eligible booking from the Bookings page before it starts. Venue or organizer policies may also apply. Repeated no-shows, abusive cancellations, or attempts to evade venue rules may lead to booking restrictions or account suspension.</p>
<h2>Sport and activity risks</h2><p>Sport and outdoor activities involve risks including collision, falls, injury, weather, equipment failure, and the actions of other participants. You are responsible for deciding whether an activity is suitable for you, following safety instructions, using appropriate equipment, and seeking medical advice when needed. PlayUp does not provide medical advice.</p>
<h2>Venues and organizers</h2><p>Independent venues, academies, activity operators, and organizers are responsible for their facilities, staff, schedules, pricing, safety procedures, permits, and the accuracy of their listings. Report inaccurate or unsafe listings through the Help center.</p>
<h2>Recordings and community conduct</h2><p>Recorded games display a notice during booking. Organizers must obtain any additional consent required at the venue. Users must respect other participants, avoid harassment and unlawful content, and must not misuse personal information, scores, messages, or recordings.</p>
<h2>Service availability</h2><p>We work to keep PlayUp available and accurate, but do not guarantee uninterrupted service or that every listing will proceed. Features may change as the pilot develops. To the extent permitted by law, PlayUp is not responsible for indirect losses or events controlled by independent venues, organizers, or participants.</p>
<h2>Suspension and termination</h2><p>We may restrict or suspend accounts to protect users, investigate abuse, comply with law, or enforce these terms. You may request account deletion from <Link className="inline-link" href="/settings/account">Account and data</Link>.</p>
<h2>Governing rules and contact</h2><p>These terms are governed by applicable laws in Jordan. Questions, complaints, and notices can be submitted through the <Link className="inline-link" href="/contact">Contact page</Link>{brand.supportEmail&&<> or emailed to <a className="inline-link" href={`mailto:${brand.supportEmail}`}>{brand.supportEmail}</a></>}.</p>
</article></main>}
