import Image from "next/image";
import Link from "next/link";
import { redirect } from "next/navigation";
import { currentUser } from "@/lib/auth";
import { bookingList } from "@/lib/booking";
import { gameDate,gameTime } from "@/lib/data";
import { cancelBookingAction } from "@/app/actions";
type BookingRow={id:string;status:string;reference:string;title:string;sport:string;starts_at:string;image_url:string;venue_name:string;area:string};
export default async function Bookings({searchParams}:{searchParams:Promise<{tab?:string;notice?:string;error?:string}>}){const user=await currentUser();if(!user)redirect("/login");const f=await searchParams;const tab=f.tab||"upcoming";const all=await bookingList(user.id) as BookingRow[];const rows=all.filter(b=>tab==="cancelled"?b.status==="CANCELLED":tab==="past"?new Date(b.starts_at)<new Date()&&b.status!=="CANCELLED":new Date(b.starts_at)>=new Date()&&b.status!=="CANCELLED");return <main className="page"><div className="container" style={{maxWidth:950}}><div className="page-head"><h1>My Bookings</h1></div>{f.notice&&<div className="alert">{f.notice}</div>}{f.error&&<div className="alert alert-error">{f.error}</div>}<div className="tabs">{["upcoming","past","cancelled"].map(t=><Link className={tab===t?"active":""} href={`/bookings?tab=${t}`} key={t}>{t[0].toUpperCase()+t.slice(1)}</Link>)}</div>{rows.length?rows.map(b=><div className="card" key={b.id} style={{display:"flex",alignItems:"center",gap:16,padding:12,marginBottom:12}}><div style={{width:104,height:72,position:"relative",flexShrink:0,borderRadius:4,overflow:"hidden"}}><Image src={b.image_url} alt="" fill sizes="104px"/></div><div style={{flex:1}}><strong>{b.title}</strong><p className="muted" style={{margin:"3px 0",fontSize:11}}>{gameDate(b.starts_at)} · {gameTime(b.starts_at)}<br/>{b.venue_name}, {b.area}</p><small className="muted">{b.reference}</small></div><span className={`badge ${b.status==="CANCELLED"?"badge-orange":"badge-green"}`}>{b.status}</span><div style={{display:"grid",gap:5}}><Link className="btn btn-outline btn-small" href={`/games/${(b as BookingRow&{game_id:string}).game_id}`}>View</Link>{tab==="upcoming"&&b.status==="CONFIRMED"&&<form action={cancelBookingAction}><input type="hidden" name="bookingId" value={b.id}/><button className="text-button" type="submit">Cancel</button></form>}</div></div>):<div className="empty"><h3>No {tab} bookings</h3><p>Find a game and get back on the field.</p><Link className="btn btn-primary" href="/games">Browse games</Link></div>}</div></main>}
