import { chromium } from "playwright";
const browser=await chromium.launch({channel:"chrome",headless:true});
const context=await browser.newContext({baseURL:"http://localhost:3000"});
const page=await context.newPage();
try{
 await page.goto("/login");
 await page.getByLabel("Email").fill("organizer@playo.local");
 await page.getByLabel("Password").fill("PlayoDemo2026!");
 await page.getByRole("button",{name:"Log In"}).click();
 await page.waitForURL("**/games",{timeout:15000});
 await page.goto("/admin/games/new");
 await page.locator('input[name="format"]').fill("5v5");
 await page.locator('input[name="title"]').fill("Smoke Test Football 5v5");
 const venue=page.locator('select[name="venueId"]');
 await venue.selectOption({label:"Al Reem Pitch (football)"});
 const date=new Date(Date.now()+7*86400000);date.setHours(19,0,0,0);
 const local=`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}T19:00`;
 await page.locator('input[name="startsAt"]').fill(local);
 await page.locator('textarea[name="description"]').fill("Local smoke test match.");
 await page.getByRole("button",{name:"Publish Game"}).click();
 await page.waitForURL("**/admin/games/*",{timeout:15000});
 if(page.url().includes("/new?error"))throw new Error("Create game failed: "+page.url());
 console.log("PASS organizer create game");
 await page.getByRole("link",{name:"Open Scorekeeper"}).click();
 await page.getByRole("button",{name:"START",exact:true}).click();
 await page.waitForTimeout(400);
 if(!((await page.locator(".scorekeeper").innerText()).includes("Running")))throw new Error("Clock did not start");
 await page.getByRole("button",{name:"PAUSE",exact:true}).click();
 await page.waitForTimeout(400);
 if(!((await page.locator(".scorekeeper").innerText()).includes("Paused")))throw new Error("Clock did not pause");
 console.log("PASS match clock start and pause");
 await page.getByRole("button",{name:"Record Event"}).click();
 await page.waitForTimeout(500);
 if(!((await page.locator(".scoreboard").innerText()).includes("1")))throw new Error("Score did not update");
 console.log("PASS football score event");
 page.once("dialog",d=>d.accept());
 await page.getByRole("button",{name:"Undo Last Event"}).click();
 await page.waitForTimeout(500);
 if(!((await page.locator(".scoreboard").innerText()).includes("0")))throw new Error("Undo did not update");
 console.log("PASS score event undo");
}finally{await browser.close();}
